FROM amazoncorretto:25.0.1-alpine
VOLUME /tmp
COPY apiEncryptionKey.jks apiEncryptionKey.jks
COPY target/VendorPovConfigServer-0.0.1-SNAPSHOT.jar ConfigServer.jar
ENTRYPOINT [ "java","-Djava.security.egd=file:/dev/./urandom","-jar","ConfigServer.jar" ]